GET http://localhost:5047/drinks
###
GET http://localhost:5047/drinks/6737a835c027c4a169777485
###
GET http://localhost:5047/drinks/byAlcohol/Vodka
###
GET http://localhost:5047/drinks/byName/Martini 
###
GET http://localhost:5047/drinks/byVibe/Fancy 

###
POST http://localhost:5047/drinks 
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Espresso Martini",
  "mainSpirit": "Vodka",
  "image": "",
  "ingredients": ["Vodka", "Espresso", "Coffee Liqueur", "Simple Syrup"],
  "measurementsOz": [2, 1, 1, 0.5],
  "bitters": ["3 dashes of Cocoa Bitters"],
  "garnish": ["3 Coffee Beans"],
  "color": "Black",
  "recommendedGlasses": ["Martini Glass", "Coupe Glass"],
  "notes": ["Nothing says depressed and anxious like a espresso"],
  "method": ["Shaken"],
  "credit": "",
  "vibe": "Modern Classic"
}
###
PUT http://localhost:5047/drinks/6737a835c027c4a169777485
Authorization: Bearer <token>
Content-Type: application/json

{
  "name": "Old Fashioned",
  "mainSpirit": "Whiskey",
  "image": "",
  "ingredients": ["Whiskey", "Luxardo Syrup"],
  "measurementsOz": [ 2, 0.75 ],
  "bitters": [ "3 dashes of Angastora Bitters", "1 dash of Orange bitters" ],
  "garnish": ["Orange Peel", "Lemon Peel"],
  "color": "Brown",
  "recommendedGlasses": ["Rocks Glass"],
  "notes": [""],
  "method": ["Stirred", "Build-In-Glass"],
  "credit": "James Bond",
  "vibe": "Fancy"
}

### 
DELETE http://localhost:5047/drinks/6737a835c027c4a169777483
Authorization: Bearer e.z4lqbrc_

###

GET http://localhost:5047/profiles/6786de2b4d277765c9e67279

###
POST http://localhost:5047/profiles/
Content-Type: application/json

{
  "userName" : "TestName2",
  "email": "test2@test.com",
  "passwordHash": "TestTestTest12345Password"
}
###
POST http://localhost:5047/profiles/login
Content-Type: application/json

{
  "Username": "TestName2",
  "password": "TestTestTest12345Password"
}