GET http://localhost:5047/drinks
###
GET http://localhost:5047/drinks/6737a835c027c4a169777485
###
GET http://localhost:5047/drinks/byAlcohol/Vodka
###
GET http://localhost:5047/drinks/byName/Martini 
###
POST http://localhost:5047/drinks 
Content-Type: application/json

{
  "name": "Espresso Martini",
  "mainSpirit": "Vodka",
  "image": "",
  "ingredients": ["Vodka", "Espresso", "Coffee Liqueur", "Simple Syrup"],
  "measurementsOz": [2, 1, 1, 0.5],
  "bitters": [],
  "garnish": ["3 Coffee Beans"],
  "color": "Black",
  "recommendedGlasses": ["Martini Glass", "Coupe Glass"],
  "notes": ["Nothing says depressed and anxious like a espresso"],
  "method": ["Shaken"],
  "credit": "",
  "vibe": "Modern Classic"
}
###
PUT http://localhost:5047/drinks/6737a835c027c4a169777483
Content-Type: application/json

{
  "name": "Old Fashioned",
  "mainSpirit": "Whiskey",
  "image": "",
  "ingredients": ["Whiskey", "Simple Syrup"],
  "measurementsOz": [ 2, 0.75 ],
  "bitters": [ "3 dashes of Angastora Bitters", "1 dash of Orange bitters" ],
  "garnish": ["Orange Peel", "Lemon Peel"],
  "color": "Brown",
  "recommendedGlasses": ["Rocks Glass"],
  "notes": [""],
  "method": ["Stirred", "Build-In-Glass"],
  "credit": "James Bond",
  "vibe": "Fancy"
}

### 
DELETE http://localhost:5047/drinks/6737a835c027c4a169777483
