GET http://localhost:5047/drinks
###
GET http://localhost:5047/drinks/1
###
GET http://localhost:5047/drinks/ByAlcohol/Whiskey
###
POST http://localhost:5047/drinks 
Content-Type: application/json

{
  "name": "Martini",
  "mainSpirit": "Gin",
  "image": "",
  "ingredients": ["Gin", "White Vermouth"],
  "measurmentsOz": [2, 0.5],
  "bitters": ["1 dash or Orange Bitters"],
  "garnish": ["An Olive", "A Lemon Peel"],
  "color": "Clear",
  "recommendedGlasses": ["Martini Glass", "Coupe Glass"],
  "notes": ["007 doesnt know how martinis work"],
  "method": ["Stirred"],
  "credit": "",
  "vibe": "Classic"
}
###
PUT http://localhost:5047/drinks/2
Content-Type: application/json

{
  "name": "Old Fashioned",
  "mainSpirit": "Whiskey",
  "image": "",
  "ingredients": ["Whiskey", "Simple Syrup"],
  "measurementsOz": [ 2, 0.75 ],
  "bitters": [ "3 dashes of Angastora Bitters", "1 dash of Orange bitters" ],
  "garnish": ["Orange Peel"],
  "color": "Brown",
  "recommendedGlasses": ["Rocks Glass"],
  "notes": [""],
  "method": ["Stirred", "Build-In-Glass"],
  "credit": "James Bond",
  "vibe": "Fancy"
}

### 
DELETE http://localhost:5047/drinks/2
